//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenadoProject.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class colaboradores
    {
        public int dpi_colaborador { get; set; }
        public string nombre_colaborador { get; set; }
        public string apellido_colaborador { get; set; }
        public string direccion_colaborador { get; set; }
        public Nullable<int> telefono_colaborador { get; set; }
        public Nullable<int> cantidad_hijos { get; set; }
        public string puesto_colaborador { get; set; }
        public Nullable<int> codigo_departamento { get; set; }
        public Nullable<double> salario_mensual { get; set; }
    
        public virtual departamento departamento { get; set; }
    }
}
