//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenadoProject.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public string email_usuario { get; set; }
        public string contraseña { get; set; }
        public string Nombre_usuario { get; set; }
        public string Apellido_usuario { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public Nullable<int> tipo { get; set; }
    
        public virtual tipo_user tipo_user { get; set; }
    }
}
